= Material reflectance schema

== metadata

Metadata about the material.


*Type:* `+object+` +
*Required:* Yes

=== name
The display name of the material, such as 'Red brick' or 'Dark asphalt'.

*Type:* `+string+` +
*Required:* Yes


=== description
Short description of the material in 2 - 3 sentences.

*Type:* `+string+` +
*Required:* Yes


=== uuid
Universally unique identifier for the material in 8-4-4-4-12 format, see cite:[uui]. The uuid stays the same, even if version is updated.

*Type:* `+string+` +
*Pattern:* `+\\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\\b$+` +
*Required:* Yes


=== materialVersion
The version number of the material, following semantic versioning (for example, '1.0.0').

*Type:* `+string+` +
*Pattern:* `+^\\d+\\.\\d+\\.\\d+$+` +
*Required:* Yes


=== openMaterialVersion
The version of the ASAM OpenMATERIAL 3D specification used, adhering to semantic versioning (for example, '1.0.0').

*Type:* `+string+` +
*Pattern:* `+^\\d+\\.\\d+\\.\\d+$+` +
*Required:* Yes


=== copyrights
Indicates copyright details, including the year and copyright holder (e.g., '© 2024 ACME Inc.').

*Type:* `+array+` +
*Required:* Yes




=== license
Describes the license for material distribution. Use an SPDX identifier for open-source licenses (for example, 'MIT'), or provide a URL or filename for proprietary licenses.

*Type:* `+string+` +
*Required:* Yes


=== authors
Lists the author(s) of the material as a name, email, or company.

*Type:* `+array+` +
*Required:* Yes




=== creationDate
The date and time of material creation, formatted as YYYYMMDDTHHMMSSZ according to ISO 8601 cite:[iso8601] (for example, '20240703T101728Z').

*Type:* `+string+` +
*Pattern:* `+^\\d{8}T\\d{6}Z$+` +
*Required:* Yes


=== sources
Sources of the reflectance data. Was it measured, simulated, or taken from literature? Multiple sources should be comma-separated.

*Type:* `+string+` +
*Required:* Yes


== reflectance

Reflectance lookup table including relevant meta data.


*Type:* `+object+` +
*Required:* Yes

=== wavelengths
List of all wavelengths in meters contained in the lookup table.

*Type:* `+array+` +
*Required:* Yes




=== lookupTable
Array of reflectance values, with each item representing a different property. The array shall be sorted based on the columns starting with the first.

*Type:* `+array+` +
*Required:* Yes


Columns of the table:

- Column 1: Wavelength of radiation in free-space in meters (m).
- Column 2: Incident elevation angle (= zenith angle) relative to the surface normal in rad.
- Column 3: Exit elevation angle (= zenith angle) relative to the surface normal in rad.
- Column 4: Exit azimuth angle in rad. For reflectance with incident and exit vectors on the same plane as the normal, exit azimuth angle is 0.
- Column 5: Polarized plane angle in rad. This is the angle between the plane containing the incident, exit, and normal vector, and the plane of polarization.
- Column 6: Amplitude within the linearly polarized plane. The amplitude is given as a relative value compared to an ideal reflector.
- Column 7: Phase within the linearly polarized plane. If the phase is not taken into account, it is null.


