= Material brdf schema

== metadata

The key meta information about the BRDF look-up table.


*Type:* `+object+` +
*Required:* Yes

=== name
The display name of the material, such as 'Red brick' or 'Dark asphalt'.

*Type:* `+string+` +
*Required:* Yes


=== description
Short description of the material in 2 - 3 sentences.

*Type:* `+string+` +
*Required:* No


=== uuid
Universally unique identifier for the material in 8-4-4-4-12 format, see cite:[uui]. The uuid stays the same, even if version is updated.

*Type:* `+string+` +
*Pattern:* `+\\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\\b$+` +
*Required:* Yes


=== materialVersion
The version number of the material, following semantic versioning (for example, '1.0.0').

*Type:* `+string+` +
*Pattern:* `+^\\d+\\.\\d+\\.\\d+$+` +
*Required:* Yes


=== openMaterialVersion
The version of the ASAM OpenMATERIAL 3D specification used, adhering to semantic versioning (for example, '1.0.0').

*Type:* `+string+` +
*Pattern:* `+^\\d+\\.\\d+\\.\\d+$+` +
*Required:* Yes


=== copyrights
Indicates copyright details, including the year and copyright holder (for example, '© 2024 ACME Inc.').

*Type:* `+array+` +
*Required:* Yes




=== license
Describes the license for material distribution. Use an SPDX identifier for open-source licenses (for example, 'MIT'), or provide a URL or filename for proprietary licenses.

*Type:* `+string+` +
*Required:* Yes


=== authors
Lists the author(s) of the material as a name, email, or company.

*Type:* `+array+` +
*Required:* Yes




=== creationDate
The date and time of material creation, formatted as YYYYMMDDTHHMMSSZ according to ISO 8601 cite:[iso8601] (for example, '20240703T101728Z').

*Type:* `+string+` +
*Pattern:* `+^\\d{8}T\\d{6}Z$+` +
*Required:* No


=== sources
Source of the BRDF data. Was it measured, simulated, or taken from literature? Multiple sources should be comma-separated.

*Type:* `+string+` +
*Required:* Yes


=== typicalSensorTechnology
Typical sensor technology this BRDF table is used for. Examples: 'radar', 'lidar', 'camera'. If more than one applies, use comma-separation.

*Type:* `+string+` +
*Required:* No


== brdf

The BRDF is used as a basic quantity to characterize the reflecting properties of a surface geometrically. The following BRDF definition applies: “The ratio of the radiance or power per unit solid-angle in the outgoing direction from a unit projected surface area to the collimated irradiance or power per unit projected surface area.” A physically plausible BRDF shall additionally obey the following three properties. (1) Positivity: The BRDF has units of inverse steradians (1/sr) and can vary from 0 to infinity. (2) Helmholtz reciprocity: It is symmetric in the incoming and outgoing direction. (3) Energy conservation: No more radiant energy is reflected from a point on the surface than incident radiant energy to that point. 


*Type:* `+object+` +
*Required:* Yes

=== wavelengths
List of all wavelengths in meters contained in the lookup table.

*Type:* `+array+` +
*Required:* Yes




=== lookupTable
Array of bidirectional reflectance distribution function (BRDF) values. The array shall be sorted based on the columns starting with the first.

*Type:* `+array+` +
*Required:* Yes


Columns of the table:

- Column 1: Wavelength of radiation in free-space in meters (m).
- Column 2: Incident elevation angle (= zenith angle) relative to the surface normal in rad.
- Column 3: Exit elevation angle (= zenith angle) relative to the surface normal in rad.
- Column 4: Exit azimuth angle in rad. For BRDFs with incident and exit vectors on the same plane as the normal, exit azimuth angle is 0.
- Column 5: BRDF value in 1/sr.


