= Material emp schema

== metadata

VERSION_V3!!_ The key meta information about the EMP look-up table.


*Type:* `+object+` +
*Required:* Yes

=== name
The display name of the material, such as 'Red brick' or 'Dark asphalt'.

*Type:* `+string+` +
*Required:* Yes


=== description
Short description of the material in 2 - 3 sentences.

*Type:* `+string+` +
*Required:* No


=== uuid
Universally unique identifier for the material in 8-4-4-4-12 format, see cite:[uui]. The uuid stays the same, even if version is updated.

*Type:* `+string+` +
*Pattern:* `+\\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\\b$+` +
*Required:* Yes


=== materialVersion
The version number of the material, following semantic versioning (for example, '1.0.0').

*Type:* `+string+` +
*Pattern:* `+^\\d+\\.\\d+\\.\\d+$+` +
*Required:* Yes


=== openMaterialVersion
The version of the ASAM OpenMATERIAL 3D specification used, adhering to semantic versioning (for example, '1.0.0').

*Type:* `+string+` +
*Pattern:* `+^\\d+\\.\\d+\\.\\d+$+` +
*Required:* Yes


=== copyrights
Indicates copyright details, including the year and copyright holder (e.g., '© 2024 ACME Inc.').

*Type:* `+array+` +
*Required:* Yes




=== license
Describes the license for material distribution. Use an SPDX identifier for open-source licenses (for example, 'MIT'), or provide a URL or filename for proprietary licenses.

*Type:* `+string+` +
*Required:* Yes


=== authors
Lists the author(s) of the material as a name, email, or company.

*Type:* `+array+` +
*Required:* Yes




=== creationDate
The date and time of material creation, formatted as YYYYMMDDTHHMMSSZ according to ISO 8601 cite:[iso8601] (for example, '20240703T101728Z').

*Type:* `+string+` +
*Pattern:* `+^\\d{8}T\\d{6}Z$+` +
*Required:* No


=== sources
Sources of the electromagnetic property data. Was it measured, simulated, or taken from literature? Multiple sources should be comma-separated.

*Type:* `+string+` +
*Required:* Yes


== electromagneticProperties

Array of electromagnetic property values, with each item representing a different property. The array shall be sorted based on the columns starting with the first.


*Type:* `+array+` +
*Required:* Yes


Columns of the table:

- Column 1: Wavelength of radiation in free-space in meters (m).
- Column 2: Temperature of material in Kelvin (K).
- Column 3: Relative humidity of material in percent (%).
- Column 4: Real part of complex permeability of material.
- Column 5: Imaginary part of complex permeability of material.
- Column 6: Real part of complex permittivity of material.
- Column 7: Imaginary part of complex permittivity of material.

