# Minimal working Antora configuration to publish to GitHub Pages
# Source: https://docs.antora.org/antora/latest/publish-to-github-pages/  (example 2)
# Output URL: https://asam-ev.github.io/OpenMATERIAL
name: Publish with Antora to GitHub Pages
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    name: Build OpenMATERIAL documentation-release and deploy it to gh-pages
    runs-on: ubuntu-latest
    services:
      kroki:
        image: yuzutech/kroki:0.15.1
        env:
          KROKI_MAX_URI_LENGTH: 8000
          KROKI_BLOCKDIAG_HOST: blockdiag
          KROKI_MERMAID_HOST: mermaid
      blockdiag:
        image: yuzutech/kroki-blockdiag:0.15.1
      mermaid:
        image: yuzutech/kroki-mermaid:0.15.1

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v4
      with:
         path: repo
         fetch-depth: 0 # test if depth in fetch history is required
         submodules: recursive

    - name: Generate AsciiDoc from JSON
      working-directory: repo/scripts
      run: |
        python3 generate_schema_docs.py

    - name: push changes to remote
      working-directory: repo/scripts
      run: |
        git config --global user.name "Martin Fiebig"
        git config --global user.email "martin.fiebig@parson-europe.com"
        git add --all; git add ../content/08_material/material-reflectance-schema.adoc
        git commit -m "test commit"
        git push

    - name: Configure Pages
      uses: actions/configure-pages@v4

    - name: Generate site
      uses: docker://ghcr.io/asam-ev/project-guide-docker:4
      with:
        entrypoint: sh
        args: repo/run-build.sh # modfied based on OSI

   

    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./repo/site

  deploy:
    # Run if it was not triggered from remote OR the remote source was master or main.
    if: ${{ github.event_name != 'repository_dispatch' || contains(github.event.client_payload.ref, 'master') || contains(github.event.client_payload.ref, 'main') }}
    # Allow one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true

    needs: build
    permissions:
      actions: read
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

